### ISSUE TITLE
runScriptJob error

### ISSUE THREAD

**Issue by pat-s** [jonocarroll/dash#1]
Hi Jonathan,

nice idea! I tried it on RStudio Server Pro and locally.

Here's what I get:

RStudio Server Pro (1.2.713) (Debian 9)

```
Fehler in .Call("rs_runScriptJob", path, encoding, workingDir, importEnv,  : 
  Falsche Anzahl von Argumenten (5), erwarte 4 für 'rs_runScriptJob'
```

Local (1.2.679) (Arch)

```
Error in .rs.api.runScriptJob(path = path.expand(tf), workingDir = getwd(),  : 
  could not find function ".rs.api.runScriptJob"
```

**Comment by jonocarroll** [comment]
I haven't tried with Server, but I'll look into that.

Is the local version recent enough? This is an unreleased, undocumented feature so perhaps try with the latest daily? 

I built/tested in Ubuntu.

Cheers!

**Comment by jonocarroll** [comment]
RIght then, I said it was bleeding edge... The arguments were changed in the last 4 days, with the addition of `encoding`. You'll need a _very_ up to date daily.

https://github.com/rstudio/rstudio/commit/f5a04602d4b8c5f73738484fe28b8073fc1f8dba?diff=unified#diff-b9b7411b38a40202c1d0b345e3dbcd2c

**Comment by pat-s** [comment]
Ok, good to know. Will try again in a few days then :)

**Comment by jonocarroll** [comment]
My guess is a minimum of 1.2.712.
